version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: dasboard_college_db
    environment:
      POSTGRES_USER: codesilva
      POSTGRES_PASSWORD: code123456
      POSTGRES_DB: dasboard_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prisma-network

volumes:
  postgres_data:

networks:
  prisma-network:
    driver: bridge
